=== caleis/gpwac/xsd/execlist.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.zeemanconsult.com"
xmlns="http://www.zeemanconsult.com"
elementFormDefault="qualified">

<!-- Define IP address type to use with multiple addresses -->
<xs:simpleType name="IPv4AddressType">
	<xs:annotation>
		<xs:documentation>IPv4 address in dot-decimal notation. Equivalent to [0-255].[0-255].[0-255].[0-255]</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])" />
	</xs:restriction>
</xs:simpleType>

<!-- Define various directory, filename and full path patterns -->
<xs:simpleType name="DirPathType">
	<xs:annotation>
		<xs:documentation>Directory path, $var allowed, absolute path or relative path allowed, cannot have / at the end</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="80"/>
		<xs:pattern value="([$][A-Za-z_][A-Za-z0-9_]*|/)(/[A-Za-z0-9._-]+)+" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="FileNameType">
	<xs:annotation>
		<xs:documentation>Filename in the format of name.ext</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="40"/>
		<xs:pattern value="^[A-Za-z0-9._-]+(\.[A-Za-z0-9._-]+)?$" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="FullPathType">
	<xs:annotation>
		<xs:documentation>Full path: absolute path, relative path, with $var allowed and with name.ext at the end</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="120"/>
		<xs:pattern value="([$][A-Za-z_][A-Za-z0-9_]*|/)(/[A-Za-z0-9._-]+)*/[A-Za-z0-9._-]+([.][A-Za-z0-9._-]+)?" />
	</xs:restriction>
</xs:simpleType>

<!-- Definition of main data structure -->
<xs:element name="execcontroldata">
   <xs:annotation>
      <xs:documentation>Execution Control List Description v0.2 - Schema Version 0.2.00, compatible with script vx.y.z</xs:documentation>
   </xs:annotation>
   <xs:complexType>
      <xs:sequence>
         <xs:element name="globalparams">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="psname"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="80"/></xs:restriction></xs:simpleType></xs:element>
                  <xs:element name="psversion"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="10"/></xs:restriction></xs:simpleType></xs:element>
 				  <xs:element name="psdate">
					  <xs:simpleType>
						 <xs:restriction base="xs:string"><xs:minLength value="10"/><xs:maxLength value="10"/>
						 <xs:pattern value="[0-3][0-9]/[0-1][0-9]/202[6-9]"/></xs:restriction>
					  </xs:simpleType>
				   </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="commonparams">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="credentials-dirpath" type="DirPathType"></xs:element>
                  <xs:element name="config-dirpath" type="DirPathType"></xs:element>
                  <xs:element name="ip-xml-dirpath" type="DirPathType"></xs:element>
                  <xs:element name="ip-xsd-fullpath"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="120"/></xs:restriction></xs:simpleType></xs:element>
                  <xs:element name="ssid-xml-dirpath" type="DirPathType"></xs:element>
                  <xs:element name="ssid-xsd-fullpath"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="120"/></xs:restriction></xs:simpleType></xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="execlist">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="execrecord" maxOccurs="100" minOccurs="1">
                     <xs:complexType>
                        <xs:sequence>
                          <xs:element name="active" type="xs:boolean"/>
						  <xs:element name="start-with-default-config" type="xs:boolean"/>
						  <xs:element name="credentials-file"><xs:simpleType>
							 <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="40"/></xs:restriction></xs:simpleType></xs:element>
						  <xs:element name="config-dir"><xs:simpleType>
							 <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="40"/></xs:restriction></xs:simpleType></xs:element>
						  <xs:element name="initial-ip-address" type="IPv4AddressType"></xs:element>
						  <xs:element name="target-ip-address" type="IPv4AddressType"></xs:element>
						  <xs:element name="ip-xml-filename"><xs:simpleType>
							 <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="40"/></xs:restriction></xs:simpleType></xs:element>
						  <xs:element name="ssid-xml-filename"><xs:simpleType>
							 <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="40"/></xs:restriction></xs:simpleType></xs:element>
                        </xs:sequence>
                     </xs:complexType>
                  </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== caleis/gpwac/xml/execlist.xml
<?xml version="1.0" ?>
<!-- Execution Control List Descriptor v0.2 -->
<!-- Compatible with version 0.1 of ssidset.xsd schema and script vx.y.z -->
<execcontroldata
xmlns="http://www.zeemanconsult.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.zeemanconsult.com /home/moxa/paramsets/execlist.xsd">
   <globalparams>
      <psname>Execution Control Data demo</psname>
      <psversion>v0.1</psversion>
	  <!-- date is expected in dd/mm/yyyy format -->
      <psdate>16/04/2026</psdate>
   </globalparams>
   <commonparams>
      <credentials-dirpath>$HOME/.gpwac</credentials-dirpath>
      <config-dirpath>$HOME/gpwac/default-configs</config-dirpath>
      <ip-xml-dirpath>$HOME/gpwac/xml</ip-xml-dirpath>
      <ip-xsd-fullpath>$HOME/gpwac/xsd/ipset.xsd</ip-xsd-fullpath>
      <ssid-xml-dirpath>$HOME/gpwac/xml</ssid-xml-dirpath>
      <ssid-xsd-fullpath>$HOME/gpwac/xsd/ssidset.xsd</ssid-xsd-fullpath>
   </commonparams>
   <execlist>
      <execrecord>
         <active>true</active>
	     <start-with-default-config>true</start-with-default-config>
         <credentials-file>southdeep-cred.age</credentials-file>
         <config-dir>awk-3252a_gfsd_recd</config-dir>
         <initial-ip-address>192.168.127.253</initial-ip-address>
         <target-ip-address>192.168.127.200</target-ip-address>
         <ip-xml-filename>ipset_1.xml</ip-xml-filename>
         <ssid-xml-filename>ssidset1.xml</ssid-xml-filename>
      </execrecord>
      <execrecord>
         <active>true</active>
	     <start-with-default-config>false</start-with-default-config>
         <credentials-file>southdeep-cred.age</credentials-file>
         <config-dir>awk-3252a_gfsd_recd</config-dir>
         <initial-ip-address>192.168.127.200</initial-ip-address>
         <target-ip-address>192.168.127.253</target-ip-address>
         <ip-xml-filename>ipset_1.xml</ip-xml-filename>
         <ssid-xml-filename>ssidset2.xml</ssid-xml-filename>
      </execrecord>
   </execlist>
</execcontroldata>
