=== caleis/gpwac/xsd/ipset.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.zeemanconsult.com"
xmlns="http://www.zeemanconsult.com"
elementFormDefault="qualified">

<!-- Define IP address type to use with multiple addresses -->
<xs:simpleType name="IPv4AddressType">
	<xs:annotation>
		<xs:documentation>IPv4 address in dot-decimal notation. Equivalent to [0-255].[0-255].[0-255].[0-255]</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])" />
	</xs:restriction>
</xs:simpleType>

<!-- Define IP address type OR empty string -->
<xs:simpleType name="IPv4AddressOrEmptyType">
	<xs:annotation>
		<xs:documentation>IPv4 address in dot-decimal notation. Equivalent to [0-255].[0-255].[0-255].[0-255]</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:pattern value="(((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5]))?" />
	</xs:restriction>
</xs:simpleType>

<!-- Dumb, but effective Netmask type with validation -->
<xs:simpleType name="IPv4NetmaskType">
  <xs:restriction base="xs:string">
	<xs:enumeration value="0.0.0.0"/>
    <xs:enumeration value="128.0.0.0"/>
    <xs:enumeration value="192.0.0.0"/>
    <xs:enumeration value="224.0.0.0"/>
    <xs:enumeration value="240.0.0.0"/>
    <xs:enumeration value="248.0.0.0"/>
    <xs:enumeration value="252.0.0.0"/>
    <xs:enumeration value="254.0.0.0"/>
    <xs:enumeration value="255.0.0.0"/>
    <xs:enumeration value="255.128.0.0"/>
    <xs:enumeration value="255.192.0.0"/>
    <xs:enumeration value="255.224.0.0"/>
    <xs:enumeration value="255.240.0.0"/>
    <xs:enumeration value="255.248.0.0"/>
    <xs:enumeration value="255.252.0.0"/>
    <xs:enumeration value="255.254.0.0"/>
    <xs:enumeration value="255.255.0.0"/>
    <xs:enumeration value="255.255.128.0"/>
    <xs:enumeration value="255.255.192.0"/>
    <xs:enumeration value="255.255.224.0"/>
    <xs:enumeration value="255.255.240.0"/>
    <xs:enumeration value="255.255.248.0"/>
    <xs:enumeration value="255.255.252.0"/>
    <xs:enumeration value="255.255.254.0"/>
    <xs:enumeration value="255.255.255.0"/>
    <xs:enumeration value="255.255.255.128"/>
    <xs:enumeration value="255.255.255.192"/>
    <xs:enumeration value="255.255.255.224"/>
    <xs:enumeration value="255.255.255.240"/>
    <xs:enumeration value="255.255.255.248"/>
    <xs:enumeration value="255.255.255.252"/>
    <xs:enumeration value="255.255.255.254"/>
    <xs:enumeration value="255.255.255.255"/>
  </xs:restriction>
</xs:simpleType>



<xs:element name="ipparameterset">
   <xs:annotation>
      <xs:documentation>IP Parameter Set Description v0.2 - Schema Version 0.2, compatible with xml2npv v0.5.xx --></xs:documentation>
   </xs:annotation>
   <xs:complexType>
      <xs:sequence>
         <xs:element name="globalparams">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="psname"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="80"/></xs:restriction></xs:simpleType></xs:element>
                  <xs:element name="psversion"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="10"/></xs:restriction></xs:simpleType></xs:element>
 				  <xs:element name="psdate">
					  <xs:simpleType>
						 <xs:restriction base="xs:string"><xs:minLength value="10"/><xs:maxLength value="10"/>
						 <xs:pattern value="[0-3][0-9]/[0-1][0-9]/202[6-9]"/></xs:restriction>
					  </xs:simpleType>
				   </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="ipset">
			 <xs:complexType>
				<xs:sequence>
					<xs:element name="netmask" type="IPv4NetmaskType"></xs:element>
					<xs:element name="defgw" type="IPv4AddressType"></xs:element>
					<xs:element name="dnsserver1" type="IPv4AddressOrEmptyType"></xs:element>
					<xs:element name="dnsserver2" type="IPv4AddressOrEmptyType"></xs:element>
				</xs:sequence>
			 </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== caleis/gpwac/xml/ipset_2.xml
<?xml version="1.0" ?>
<!-- IP Parameter Set Descriptor v0.2 -->
<!-- Compatible with version 0.2 of ipset.xsd schema and xml2nvp v0.5.xx -->
<ipparameterset
xmlns="http://www.zeemanconsult.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.zeemanconsult.com /home/moxa/paramsets/ipset.xsd">
	<globalparams>
		<psname>IP parameter set #2: demo</psname>
		<psversion>v0.1</psversion>
		<!-- date is expected in dd/mm/yyyy format -->
		<psdate>26/02/2026</psdate>
	</globalparams>
	<ipset>
        <netmask>255.255.255.0</netmask>
        <defgw>192.168.127.2</defgw>
        <dnsserver1>1.2.3.4</dnsserver1>
        <dnsserver2>4.4.4.4</dnsserver2>
    </ipset>
</ipparameterset>
