=== caleis/gpwac/xsd/ssidset.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.zeemanconsult.com"
xmlns="http://www.zeemanconsult.com"
elementFormDefault="qualified">
<xs:element name="ssidparameterset">
   <xs:annotation>
      <xs:documentation>SSID Parameter Set Description v0.2 - Schema Version 0.2, compatible with script vx.y.z</xs:documentation>
   </xs:annotation>
   <xs:complexType>
      <xs:sequence>
         <xs:element name="globalparams">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="psname"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="80"/></xs:restriction></xs:simpleType></xs:element>
                  <xs:element name="psversion"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="10"/></xs:restriction></xs:simpleType></xs:element>
 				  <xs:element name="psdate">
					  <xs:simpleType>
						 <xs:restriction base="xs:string"><xs:minLength value="10"/><xs:maxLength value="10"/>
						 <xs:pattern value="[0-3][0-9]/[0-1][0-9]/202[6-9]"/></xs:restriction>
					  </xs:simpleType>
				   </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="ssidsets">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="ssidset" maxOccurs="9" minOccurs="1">
                     <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ssidstatus" type="xs:boolean"/>
							<xs:element name="ssidname"><xs:simpleType>
								<xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="32"/></xs:restriction></xs:simpleType></xs:element>
							<xs:element name="rfband">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="5ghz"/>
										<xs:enumeration value="2.4ghz"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ssidbroadcast" type="xs:boolean"/>
							<xs:element name="wpa-encryption">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="aes"/>
										<xs:enumeration value="tkip-aes-mixed"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="wpa-passphrase"><xs:simpleType>
								<xs:restriction base="xs:string"><xs:minLength value="8"/><xs:maxLength value="63"/></xs:restriction></xs:simpleType></xs:element>
							<xs:element name="pvid"><xs:simpleType>
								<xs:restriction base="xs:unsignedInt"><xs:minInclusive value="1"/><xs:maxInclusive value="4094"/></xs:restriction></xs:simpleType></xs:element>                         </xs:sequence>
                     </xs:complexType>
                  </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== caleis/gpwac/xml/ssidset1.xml
<?xml version="1.0" ?>
<!-- SSID Parameter Set Descriptor v0.1 -->
<!-- Compatible with version 0.2 of ssidset.xsd schema and script vx.y.z -->
<ssidparameterset
xmlns="http://www.zeemanconsult.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.zeemanconsult.com /home/moxa/paramsets/ssidset.xsd">
   <globalparams>
      <psname>SSID parameter set #1: demo</psname>
      <psversion>v0.1</psversion>
	  <!-- date is expected in dd/mm/yyyy format -->
      <psdate>16/02/2026</psdate>
   </globalparams>
   <ssidsets>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid1</ssidname>
         <rfband>5ghz</rfband>
         <ssidbroadcast>true</ssidbroadcast>
		 <wpa-encryption>aes</wpa-encryption>
         <wpa-passphrase>wpa-passphraseTest1</wpa-passphrase>
		 <pvid>124</pvid>
      </ssidset>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid2</ssidname>
         <rfband>5ghz</rfband>
         <ssidbroadcast>true</ssidbroadcast>
		 <wpa-encryption>aes</wpa-encryption>
         <wpa-passphrase>WpaSecret2</wpa-passphrase>
		 <pvid>124</pvid>
      </ssidset>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid3</ssidname>
         <rfband>2.4ghz</rfband>
         <ssidbroadcast>false</ssidbroadcast>
		 <wpa-encryption>tkip-aes-mixed</wpa-encryption>
         <wpa-passphrase>wpa-passphraseTest3</wpa-passphrase>
		 <pvid>124</pvid>
      </ssidset>
   </ssidsets>
</ssidparameterset>

=== caleis/gpwac/xml/ssidset.xml
<?xml version="1.0" ?>
<!-- SSID Parameter Set Descriptor v0.1 -->
<!-- Compatible with version 0.1 of ssidset.xsd schema and script vx.y.z -->
<ssidparameterset
xmlns="http://www.zeemanconsult.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.zeemanconsult.com /home/moxa/paramsets/ssidset.xsd">
   <globalparams>
      <psname>SSID parameter set #1: demo</psname>
      <psversion>v0.1</psversion>
	  <!-- date is expected in dd/mm/yyyy format -->
      <psdate>16/02/2026</psdate>
   </globalparams>
   <ssidsets>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid1</ssidname>
         <rfband>5ghz</rfband>
         <ssidbroadcast>true</ssidbroadcast>
         <wpa-passphrase>wpa-passphraseTest1</wpa-passphrase>
      </ssidset>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid2</ssidname>
         <rfband>5ghz</rfband>
         <ssidbroadcast>false</ssidbroadcast>
         <wpa-passphrase>WpaSecret2</wpa-passphrase>
      </ssidset>
      <ssidset>
         <ssidstatus>true</ssidstatus>
         <ssidname>testssid3</ssidname>
         <rfband>2.4ghz</rfband>
         <ssidbroadcast>true</ssidbroadcast>
         <wpa-passphrase>wpa-passphraseTest3</wpa-passphrase>
      </ssidset>
   </ssidsets>
</ssidparameterset>
