=== caleis/gpwac/xsd/vlanset.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.zeemanconsult.com"
xmlns="http://www.zeemanconsult.com"
elementFormDefault="qualified">
<xs:element name="vlanparameterset">
   <xs:annotation>
      <xs:documentation>VLAN Parameter Set Description v0.1 - Schema Version 0.1, compatible with script vx.y.z</xs:documentation>
   </xs:annotation>
   <xs:complexType>
      <xs:sequence>
         <xs:element name="globalparams">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="psname"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="80"/></xs:restriction></xs:simpleType></xs:element>
                  <xs:element name="psversion"><xs:simpleType>
                     <xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="10"/></xs:restriction></xs:simpleType></xs:element>
 				  <xs:element name="psdate">
					  <xs:simpleType>
						 <xs:restriction base="xs:string"><xs:minLength value="10"/><xs:maxLength value="10"/>
						 <xs:pattern value="[0-3][0-9]/[0-1][0-9]/202[6-9]"/></xs:restriction>
					  </xs:simpleType>
				   </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="vlansets">
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="vlanset" maxOccurs="9" minOccurs="1">
                     <xs:complexType>
                        <xs:sequence>
							<xs:element name="interface"><xs:simpleType>
								<xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="32"/></xs:restriction></xs:simpleType></xs:element>
							<xs:element name="pvid"><xs:simpleType>
								<xs:restriction base="xs:unsignedInt"><xs:minInclusive value="1"/><xs:maxInclusive value="4094"/></xs:restriction></xs:simpleType></xs:element>
                        </xs:sequence>
                     </xs:complexType>
                  </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== caleis/gpwac/xml/vlanset.xml
<?xml version="1.0" ?>
<!-- VLAN Parameter Set Descriptor v0.1 -->
<!-- Compatible with version 0.1 of vlanset.xsd schema and script vx.y.z -->
<vlanparameterset
xmlns="http://www.zeemanconsult.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.zeemanconsult.com /home/moxa/paramsets/vlanset.xsd">
   <globalparams>
      <psname>VLAN parameter set #1: demo</psname>
      <psversion>v0.1</psversion>
	  <!-- date is expected in dd/mm/yyyy format -->
      <psdate>16/02/2026</psdate>
   </globalparams>
   <vlansets>
      <vlanset>
         <interface>testssid1</interface>
         <pvid>209</pvid>
      </vlanset>
      <vlanset>
         <interface>testssid2</interface>
         <pvid>2009</pvid>
      </vlanset>
      <vlanset>
         <interface>testssid3</interface>
         <pvid>4094</pvid>
      </vlanset>
   </vlansets>
</vlanparameterset>
